import Head from "next/head";
import Intro from "../components/Intro";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>jpviegas | Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={(styles.main, "global")}>
        <Intro />
      </main>
    </div>
  );
}
